config/routes.rb
Rails.application.routes.draw do
  
  # OPTIMIZE the routes needs to be added so
  # NO LOGIN 
  # / => points to the sign-up/login screen
  # /error

  # LOGIN
  # /dashbord ==> all routes
  # /patiensts ==> all routes
  # Divide the Page Like
  # mount ==> resource ==> individual request
  # Add the 404,internal Server Error


  resources :patients
  root "pages#index"

  mount Flipper::UI.app(Flipper) => "/flipper" if Rails.env.development?

  devise_for :users do
    authenticated :user do
      root :to => 'dashboards#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'session#new', as: :unauthenticated_root
    end
  end

  resources :dashboards, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "created_by", optional: true
  scope :latest, -> { order(created_at: :desc) }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  before_action :authenticate_user!
  before_action :set_dashboard
  allow_browser versions: :modern
  
#FIXME this needs to be set at dashboard controller
  def set_dashboard
    return if current_user.nil?
    if current_user.has_role?(:doctor)
      @dashboard_view = 'doctor_dashboard'
    elsif current_user.has_role?(:receptionist)
      @dashboard_view = 'receptionist_dashboard'
    end
  end

  def after_sign_in_path_for(resource)
    dashboards_path
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  layout 'layouts/dashboard'
  # TODO add a way to organize this code in helper and insure to use restfull resource
  def index
    if @dashboard_view == 'doctor_dashboard'
      chart_data_vaiue
      render 'dashboards/doctor_dashboard'
    elsif @dashboard_view == 'receptionist_dashboard'
      render 'dashboards/receptionist_dashboard'
    else
      redirect_to root_path, alert: 'Unauthorized access!'
    end
  end
  private

  def chart_data_vaiue
    obj = Patient.pluck(:created_at).uniq.map{|i| i.to_date.to_s}
    @chart_data = {
      labels: obj.uniq,
      datasets: [{
        label: 'Monthly Data',
        backgroundColor: 'transparent',
        borderColor: '#3B82F6',
        data: obj.tally.values
      }]
    }
    @chart_options = {
      responsive: true,
      maintainAspectRatio: false,
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        }
    }

    @chart_circle_data = {
      labels: [
        'Red',
        'Blue',
        'Yellow'
      ],
      datasets: [{
        label: 'My First Dataset',
        data: [300, 50, 100],
        backgroundColor: [
          'rgb(255, 99, 132)',
          'rgb(54, 162, 235)',
          'rgb(255, 205, 86)'
        ],
        hoverOffset: 4
      }]
    };
    @chart_circle_options =  {
      responsive: true
    };
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    layout 'layouts/application'
    def index
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  layout 'layouts/dashboard'
  before_action :authenticate_user!
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.latest
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.created_by = current_user.id
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_path, status: :see_other, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :phone_number, :date_of_birth, :gender, :address, :created_by)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_icon(icon, classes: nil)
    classes ||= ""
    render "icons/#{icon}", classes: classes
  end
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

# rubocop:disable Metrics/AbcSize, Metrics/MethodLength
# devise helper
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, "- #{msg}.") }
                       .join
    sentence = I18n.t(
      "errors.messages.not_saved",
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = "Ooops!"
    if resource.errors.count == 1
      message =  resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{message}.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, "#{msg}.") }
                         .join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end
# rubocop:enable Metrics/AbcSize, Metrics/MethodLength

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/dashboards/doctor_dashboard.html.erb
<div class="grid grid-cols-1 gap-2 px-2 py-2 sm:grid-cols-2 md:grid-cols-3">
  <div class="w-50% flex h-40 flex-col justify-between rounded-2xl bg-sky-500 p-4 shadow-xl">
    <div class="flex items-start justify-between">
      <h2 class="text-xl font-semibold text-white">New Users</h2>
      <%=render_icon "users",classes: "h-6 w-6 text-white"%>
    </div>

    <div class="flex items-baseline space-x-2">
      <h3 class="text-2xl font-bold text-white">800</h3>
    </div>

    <div class="flex items-center space-x-1 text-sm text-green-300">
      <span>+1200</span>
      <span class="text-white">Number of users</span>
    </div>
  </div>
  <div class="w-50% h-40 rounded-xl bg-gray-300">
    <div class="w-50% flex h-40 flex-col justify-between rounded-2xl bg-sky-500 p-4 shadow-xl">
      <div class="flex items-start justify-between">
        <h2 class="text-xl font-semibold text-white">Sales</h2>
        <%=render_icon "money",classes: "h-6 w-6 text-white"%>
      </div>

      <div class="flex items-baseline space-x-2">
        <h3 class="text-2xl font-bold text-white">₹54,000</h3>
      </div>

      <div class="flex items-center space-x-1 text-sm text-green-300">
        <span>+20.9₹</span>
        <span class="text-white">Number of sales</span>
      </div>
    </div>
  </div>
  <div class="w-50% h-40 rounded-xl bg-gray-300">
    <div class="w-50% flex h-40 flex-col justify-between rounded-2xl bg-sky-500 p-4 shadow-xl">
      <div class="flex items-start justify-between">
        <h2 class="text-xl font-semibold text-white">Repeat User</h2>
     <%=render_icon "user",classes: "h-6 w-6 text-white"%>
      </div>

      <div class="flex items-baseline space-x-2">
        <h3 class="text-2xl font-bold text-white">200</h3>
   

      </div>
      <div class="flex items-center space-x-1 text-sm text-green-300">
        <span>+50</span>
        <span class="text-white">Number of repeat user</span>
      </div>
    </div>
  </div>
</div>



<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 px-4 py-4 leading-10">
  <div class="border-sky-500 sm:col-span-2 h-60 w-auto w-full rounded-xl border bg-transparent p-4">
  <canvas class="w-full h-full"
      data-controller="chart"
      data-chart-data-value="<%= @chart_data.to_json %>"
      data-chart-options-value="<%= @chart_options.to_json %>"
  ></canvas>
  </div>
  <div class="border-sky-500 h-60 w-full rounded-xl border bg-transparent p-4">
  <canvas class="w-full h-full"
    data-controller="chart"
    data-chart-type-value="doughnut"
    data-chart-data-value="<%= @chart_circle_data.to_json %>"
    data-chart-options-value="<%= @chart_circle_options.to_json %>">
  </canvas>
  </div>
</div>

app/views/dashboards/receptionist_dashboard.html.erb
<div class="dashboard">
  <div class="tasks">
    <h3>Tasks</h3>
    <!-- Add logic to list tasks -->
  </div>
  <div class="patients">
    <h3>Patients</h3>
    <!-- Add logic to list patients -->
  </div>
  <div>
    <%= link_to 'Create New Patient', new_patient_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/icons/_accept.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 <%= classes %>">
  <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 0 1 .143 1.052l-8 10.5a.75.75 0 0 1-1.127.075l-4.5-4.5a.75.75 0 0 1 1.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 0 1 1.05-.143Z" clip-rule="evenodd" />
</svg>

app/views/icons/_delete.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 <%= classes %>">
  <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 0 0 6 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 1 0 .23 1.482l.149-.022.841 10.518A2.75 2.75 0 0 0 7.596 19h4.807a2.75 2.75 0 0 0 2.742-2.53l.841-10.52.149.023a.75.75 0 0 0 .23-1.482A41.03 41.03 0 0 0 14 4.193V3.75A2.75 2.75 0 0 0 11.25 1h-2.5ZM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4ZM8.58 7.72a.75.75 0 0 0-1.5.06l.3 7.5a.75.75 0 1 0 1.5-.06l-.3-7.5Zm4.34.06a.75.75 0 1 0-1.5-.06l-.3 7.5a.75.75 0 1 0 1.5.06l.3-7.5Z" clip-rule="evenodd" />
</svg>

app/views/icons/_home.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 <%= classes %>">
  <path fill-rule="evenodd" d="M9.293 2.293a1 1 0 0 1 1.414 0l7 7A1 1 0 0 1 17 11h-1v6a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-6H3a1 1 0 0 1-.707-1.707l7-7Z" clip-rule="evenodd" />
</svg>

app/views/icons/_info.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 <%= classes %>">
  <path fill-rule="evenodd" d="M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-7-4a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM9 9a.75.75 0 0 0 0 1.5h.253a.25.25 0 0 1 .244.304l-.459 2.066A1.75 1.75 0 0 0 10.747 15H11a.75.75 0 0 0 0-1.5h-.253a.25.25 0 0 1-.244-.304l.459-2.066A1.75 1.75 0 0 0 9.253 9H9Z" clip-rule="evenodd" />
</svg>

app/views/icons/_money.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="<%= classes%>">
  <path fill-rule="evenodd" d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16ZM6 5.75A.75.75 0 0 1 6.75 5h6.5a.75.75 0 0 1 0 1.5h-2.127c.4.5.683 1.096.807 1.75h1.32a.75.75 0 0 1 0 1.5h-1.32a4.003 4.003 0 0 1-3.404 3.216l1.754 1.754a.75.75 0 0 1-1.06 1.06l-3-3a.75.75 0 0 1 .53-1.28H8c1.12 0 2.067-.736 2.386-1.75H6.75a.75.75 0 0 1 0-1.5h3.636A2.501 2.501 0 0 0 8 6.5H6.75A.75.75 0 0 1 6 5.75Z" clip-rule="evenodd" />
</svg>

app/views/icons/_play.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 <%= classes%>">
  <path fill-rule="evenodd" d="M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0Zm6.39-2.908a.75.75 0 0 1 .766.027l3.5 2.25a.75.75 0 0 1 0 1.262l-3.5 2.25A.75.75 0 0 1 8 12.25v-4.5a.75.75 0 0 1 .39-.658Z" clip-rule="evenodd" />
</svg>

app/views/icons/_update.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5 <%= classes %>">
  <path d="m2.695 14.762-1.262 3.155a.5.5 0 0 0 .65.65l3.155-1.262a4 4 0 0 0 1.343-.886L17.5 5.501a2.121 2.121 0 0 0-3-3L3.58 13.419a4 4 0 0 0-.885 1.343Z" />
</svg>

app/views/icons/_user.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"  class="size-5 <%= classes %>">
  <path d="M10 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM3.465 14.493a1.23 1.23 0 0 0 .41 1.412A9.957 9.957 0 0 0 10 18c2.31 0 4.438-.784 6.131-2.1.43-.333.604-.903.408-1.41a7.002 7.002 0 0 0-13.074.003Z" />
</svg>

app/views/icons/_users.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="<%= classes %>">
    <path d="M7 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM14.5 9a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5ZM1.615 16.428a1.224 1.224 0 0 1-.569-1.175 6.002 6.002 0 0 1 11.908 0c.058.467-.172.92-.57 1.174A9.953 9.953 0 0 1 7 18a9.953 9.953 0 0 1-5.385-1.572ZM14.5 16h-.106c.07-.297.088-.611.048-.933a7.47 7.47 0 0 0-1.588-3.755 4.502 4.502 0 0 1 5.874 2.636.818.818 0 0 1-.36.98A7.465 7.465 0 0 1 14.5 16Z" />
</svg>

app/views/layouts/_sidebar.html.erb
<nav class="bg-slate-400 hidden md:flex flex-col text-center p-4 justify-between sticky top-20 h-[calc(100vh-80px)]" data-controller="sidebar" data-expanded="<%= (cookies[:sidebar_expanded] || true) %>">
  <div class="flex flex-col text-left">  
      <% if current_user.present? && current_user.has_role?(:doctor) %>
          <%= link_to dashboards_path do %>
            <%= render_icon 'home', classes: 'inline h-5 w-5' %>
            <span class="[[data-expanded=false]_&]:hidden">Home</span>
          <% end %>
      <% else %>
        <%= link_to dashboards_path do %>
          <span>🏠</span>
          <span class="[[data-expanded=false]_&]:hidden">Home</span>
        <% end %>
      <% end %>
    <%= link_to new_patient_path do %>
      <span>🔘</span>
      <span class="[[data-expanded=false]_&]:hidden">Buttons</span>
    <% end %>

  </div>
  <div class="text-left">
    <%= link_to "javascript:void(0)", data: { action: "click->sidebar#toggle" } do %>
      <span class="[[data-expanded=true]_&]:hidden">➡️</span>
      <span class="[[data-expanded=false]_&]:hidden">⬅️</span>
      <span class="[[data-expanded=false]_&]:hidden">Toggle</span>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Appointment" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="bg-slate-300 flex">
      <%= render 'layouts/sidebar' %>
      <main class="bg-slate-500 w-5/6 p-4 flex-grow">
        <%= Time.zone.now %>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Appointment" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="bg-slate-300 flex">
      <%= render 'layouts/sidebar' %>
      <main class="bg-slate-50 w-5/6 p-4 flex-grow">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
hello

app/views/patients/_form.html.erb
<%= form_with(model: patient, class: "contents") do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_area :address, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<tr class="py-5 hover:bg-slate-100">
  <td class="text-sm py-5 border-y text-center"><%= patient.first_name %></td>
  <td class="text-sm py-5 border-y text-center "><%= patient.last_name %></td>
  <td class="text-sm hidden md:table-cell py-5 border-y text-center"><%= patient.email %></td>
  <td class="text-sm py-5 border-y text-center "><%= patient.phone_number %></td>
  <td class="text-sm hidden md:table-cell py-5 border-y text-center "><%= patient.date_of_birth %></td>
  <td class="text-sm hidden md:table-cell py-5 border-y text-center "><%= patient.gender %></td>
  <td class="text-sm hidden md:table-cell py-5 border-y text-center "><%= patient.address %></td>
  <td class="text-sm py-5 border-y text-center text-wrap truncate"><%= patient&.creator&.email %></td>
  <td class="text-sm py-5 border-y justify-center flex">
    <%= link_to 'javascript:void(0)', data: { action: "dialog#open", value: "#{patient.id}" }, class: "ml-2 rounded-lg py-2 px-3 sm:py-3 sm:px-4 bg-gray-100 inline-block font-medium cursor-pointer" do %>
      <%= render_icon 'info', classes: 'h-2 w-2 sm:h-5 sm:w-5' %>
    <% end %>
    <%= link_to edit_patient_path(patient), class: "ml-2 rounded-lg py-2 px-3 sm:py-3 sm:px-4 bg-gray-100 inline-block font-medium cursor-pointer" do %>
    <%= render_icon 'update', classes: 'h-2 w-2 sm:h-5 sm:w-5' %>
    <% end %>
    <%= link_to patient_path(patient), data: { "turbo-method": :delete }, class: "ml-2 rounded-lg py-2 px-3 sm:py-3 sm:px-4 bg-red-500 inline-block font-medium cursor-pointer"  do %>
      <%= render_icon 'delete', classes: 'h-2 w-2 sm:h-5 sm:w-5' %>
    <% end %>
  </td>
</tr>

app/views/patients/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing patient</h1>

  <%= render "form", patient: @patient %>

  <%= link_to "Show this patient", @patient, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/patients/index.html.erb
<div class="w-full mt-5">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Patients" %>

  <div class="flex justify-between items-center" data-controller="hello">
    <h1 class="font-bold text-4xl">Patients</h1>
    <%= link_to "New patient", new_patient_path, class: "rounded-lg py-3 px-5 text-white block font-medium bg-blue-600 hover:bg-blue-500" %>
  </div>

  <div id="patients" class="min-w-full mt-10" data-controller="dialog" data-action="click->dialog#backdropClose">
    <div class="relative overflow-hidden shadow-md">
      <table class="table-fixed w-full text-left">
        <thead class="uppercase bg-[#175ade] text-[#e5e7eb]" style="background-color: #175ade; color: #e5e7eb;">
            <tr>
              <th class="py-1 border text-center font-bold p-4">First name</th>
              <th class="py-1 border text-center font-bold p-4">Last name</th>
              <th class="hidden md:table-cell py-1 border text-center font-bold p-4">Email</th>
              <th class="py-1 border text-center font-bold p-4">Phone number</th>
              <th class="hidden md:table-cell py-1 border text-center font-bold p-4">Date of birth</th>
              <th class="hidden md:table-cell py-1 border text-center font-bold p-4">Gender</th>
              <th class="hidden md:table-cell py-1 border text-center font-bold p-4">Address</th>
              <th class="py-1 border text-center font-bold p-4">Created by</th>
              <th class="py-1 border text-center font-bold p-4">Actions</th>
            </tr>
        </thead>
        <tbody class="bg-white text-gray-500 bg-[#ffffff] text-[#000000]" style="background-color: #ffffff; color: #000000;">
            <% @patients.each do |patient| %>
              <%= render patient %>
            <% end %>
        </tbody>
      </table>
    </div>
    <%= render 'shared/form_modal'%>
  </div>
</div>